services:
  baka_site:
    container_name: baka_site
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    networks:
      - caddy

networks:
  caddy:
    external: true